import json
import re

import openpyxl

DAYS_XLSX = "branches_with_waze_links_v3_days.xlsx"
ALL_XLSX = "branches_with_waze_links_v3.xlsx"
OUT_JS = "docs/data.js"

coord_re = re.compile(r"^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$")


def parse_coords(s):
    if not s:
        return None
    m = coord_re.match(s)
    if not m:
        return None
    return {"lat": float(m.group(1)), "lon": float(m.group(2))}


# ---- day routes ----
wb = openpyxl.load_workbook(DAYS_XLSX, data_only=True)
route_ws = wb["Route"]

days = {}
unscheduled = []
for row in route_ws.iter_rows(min_row=2, values_only=True):
    day, stop, orig, corrected, waze, coords, leg = row
    entry = {
        "originalText": orig,
        "correctedText": corrected,
        "wazeUrl": waze,
        "coordinates": parse_coords(coords),
        "legDistanceM": int(leg) if leg is not None else None,
    }
    if day == "Unscheduled":
        unscheduled.append(entry)
    else:
        days.setdefault(int(day), []).append({**entry, "stop": int(stop)})

day_list = []
for day_num in sorted(days):
    stops = sorted(days[day_num], key=lambda s: s["stop"])
    total = sum(s["legDistanceM"] for s in stops if s["legDistanceM"])
    day_list.append({"day": day_num, "stops": stops, "totalDistanceM": total})

# ---- full branch database ----
wb2 = openpyxl.load_workbook(ALL_XLSX, data_only=True)
all_ws = wb2.active

# map (originalText) -> (day, stop) for cross-referencing
schedule_lookup = {}
for d in day_list:
    for s in d["stops"]:
        schedule_lookup[s["originalText"]] = {"day": d["day"], "stop": s["stop"]}

all_branches = []
for row in all_ws.iter_rows(min_row=2, values_only=True):
    orig, corrected, waze, coords, closest_idx, closest_m = row
    sched = schedule_lookup.get(orig)
    all_branches.append({
        "originalText": orig,
        "correctedText": corrected,
        "wazeUrl": waze,
        "coordinates": parse_coords(coords),
        "closestDistanceM": int(closest_m) if closest_m is not None else None,
        "day": sched["day"] if sched else None,
        "stop": sched["stop"] if sched else None,
    })

data = {
    "generated": True,
    "days": day_list,
    "unscheduled": unscheduled,
    "allBranches": all_branches,
}

with open(OUT_JS, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by scripts/build_site_data.py — do not edit by hand.\n")
    f.write("window.APP_DATA = ")
    f.write(json.dumps(data, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"wrote {OUT_JS}: {len(day_list)} days, {sum(len(d['stops']) for d in day_list)} scheduled stops, "
      f"{len(unscheduled)} unscheduled, {len(all_branches)} total branches")
