import json
import os
import re
import urllib.parse

import openpyxl

DAYS_XLSX = "branches_with_waze_links_v3_days.xlsx"
ALL_XLSX = "branches_with_waze_links_v3.xlsx"
DRIVING_JSON = "driving_routes.json"
OUT_JS = "docs/data.js"

driving = {}
if os.path.exists(DRIVING_JSON):
    with open(DRIVING_JSON, encoding="utf-8") as f:
        driving = {int(k): v for k, v in json.load(f).items()}
else:
    print(f"warning: {DRIVING_JSON} not found — run scripts/fetch_driving_distances.py first; "
          "site will fall back to straight-line distances only")


def google_maps_url(stops):
    pts = [f"{s['coordinates']['lat']},{s['coordinates']['lon']}" for s in stops if s["coordinates"]]
    if len(pts) < 2:
        return None
    origin, destination = pts[0], pts[-1]
    waypoints = pts[1:-1]
    params = {"api": "1", "origin": origin, "destination": destination, "travelmode": "driving"}
    if waypoints:
        params["waypoints"] = "|".join(waypoints)
    return "https://www.google.com/maps/dir/?" + urllib.parse.urlencode(params, safe="|,")

coord_re = re.compile(r"^\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*$")


def parse_coords(s):
    if not s:
        return None
    m = coord_re.match(s)
    if not m:
        return None
    return {"lat": float(m.group(1)), "lon": float(m.group(2))}


# ---- day routes ----
wb = openpyxl.load_workbook(DAYS_XLSX, data_only=True)
route_ws = wb["Route"]

days = {}
unscheduled = []
for row in route_ws.iter_rows(min_row=2, values_only=True):
    day, stop, orig, corrected, waze, coords, leg = row
    entry = {
        "originalText": orig,
        "correctedText": corrected,
        "wazeUrl": waze,
        "coordinates": parse_coords(coords),
        "legDistanceM": int(leg) if leg is not None else None,
    }
    if day == "Unscheduled":
        unscheduled.append(entry)
    else:
        days.setdefault(int(day), []).append({**entry, "stop": int(stop)})

day_list = []
for day_num in sorted(days):
    stops = sorted(days[day_num], key=lambda s: s["stop"])
    total = sum(s["legDistanceM"] for s in stops if s["legDistanceM"])

    drv = driving.get(day_num)
    if drv:
        for i, s in enumerate(stops):
            if i > 0:
                leg = drv["legs"][i - 1]
                s["legDrivingDistanceM"] = leg["distanceM"]
                s["legDrivingDurationS"] = leg["durationS"]

    day_entry = {
        "day": day_num,
        "stops": stops,
        "totalDistanceM": total,
        "drivingDistanceM": drv["totalDistanceM"] if drv else None,
        "drivingDurationS": drv["totalDurationS"] if drv else None,
        "routeGeometry": drv["geometry"] if drv else None,
        "googleMapsUrl": google_maps_url(stops),
    }
    day_list.append(day_entry)

# ---- full branch database ----
wb2 = openpyxl.load_workbook(ALL_XLSX, data_only=True)
all_ws = wb2.active

# map (originalText) -> (day, stop) for cross-referencing
schedule_lookup = {}
for d in day_list:
    for s in d["stops"]:
        schedule_lookup[s["originalText"]] = {"day": d["day"], "stop": s["stop"]}

all_branches = []
for row in all_ws.iter_rows(min_row=2, values_only=True):
    orig, corrected, waze, coords, closest_idx, closest_m = row
    sched = schedule_lookup.get(orig)
    all_branches.append({
        "originalText": orig,
        "correctedText": corrected,
        "wazeUrl": waze,
        "coordinates": parse_coords(coords),
        "closestDistanceM": int(closest_m) if closest_m is not None else None,
        "day": sched["day"] if sched else None,
        "stop": sched["stop"] if sched else None,
    })

data = {
    "generated": True,
    "days": day_list,
    "unscheduled": unscheduled,
    "allBranches": all_branches,
}

with open(OUT_JS, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by scripts/build_site_data.py — do not edit by hand.\n")
    f.write("window.APP_DATA = ")
    f.write(json.dumps(data, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"wrote {OUT_JS}: {len(day_list)} days, {sum(len(d['stops']) for d in day_list)} scheduled stops, "
      f"{len(unscheduled)} unscheduled, {len(all_branches)} total branches")
